language: php
php:
  - 5.6
  - 7.2

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
  matrix:
    - MAGENTO_VERSION=1.9.3.3
    - MAGENTO_VERSION=1.9.4.0
    - MAGENTO_VERSION=2.3.0

matrix:
  exclude:
    - php: 5.6
      env: MAGENTO_VERSION=1.9.4.0
    - php: 5.6
      env: MAGENTO_VERSION=2.3.0
    - php: 7.2
      env: MAGENTO_VERSION=1.9.3.3

services:
  - docker

script:
  - PHP_VERSION=$(php -v | grep "^PHP" | awk '{print $2}' | sed "s/-.*//" | grep -o "^[^\.]*\.\?[^\.]*")
  - docker build -t bliskapaczkapl/magento_base:${PHP_VERSION}_${MAGENTO_VERSION} -f magento-$MAGENTO_VERSION/Dockerfile-php$PHP_VERSION .
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push bliskapaczkapl/magento_base:${PHP_VERSION}_${MAGENTO_VERSION};
    fi
