language: php
php:
  - 5.6
  - 7.2

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
  matrix:
    - MAGENTO_VERSION=1.9.3.3
    - MAGENTO_VERSION=1.9.4.0

matrix:
  exclude:
    - php: 5.6
      env: MAGENTO_VERSION=1.9.4.0
    - php: 7.2
      env: MAGENTO_VERSION=1.9.3.3

services:
  - docker

script:
  - PHP_VERSION=$(php -v | grep "^PHP" | awk '{print $2}' | sed "s/-.*//" | grep -o "^[^\.]*\.\?[^\.]*")
  - docker build -t bliskapaczkapl/magento_base:$PHP_VERSION_$MAGENTO_VERSION -t bliskapaczkapl/magento_base:latest -f magento/Dockerfile-php$PHP_VERSION .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push bliskapaczkapl/magento_base:${PHP_VERSION}_${MAGENTO_VERSION}

jobs:
  include:
    - stage: push
      script:
        - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
          docker push bliskapaczkapl/magento_base:latest;
          fi
      php: 5.6
