FROM php:7.1-fpm

MAINTAINER Mateusz Koszutowski <mkoszutowski@divante.pl>

ENV magento_path /var/www/magento
ENV magento_version 2.2.5
WORKDIR ${magento_path}

RUN apt-get update \
    && apt-get install -y \
        python-setuptools \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        libmcrypt-dev \
        libicu-dev \
        libxslt-dev \
        cron \
        mc \
        nano \
        mysql-client \
    && docker-php-ext-install \
        pdo_mysql \
        mysqli \
        intl \
        xsl \
        soap \
        bcmath \
        zip \
        mcrypt \
    && docker-php-ext-configure gd \
        --with-freetype-dir=/usr/include/ \
        --with-jpeg-dir=/usr/include/ \
        --with-png-dir=/usr/include/ \
    && docker-php-ext-install gd \
    && apt-get purge -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        libmcrypt-dev \
        libicu-dev \
        libxslt-dev \
    && apt-get install -y gnupg \
    && curl http://nginx.org/keys/nginx_signing.key | apt-key add - \
    && echo "deb http://nginx.org/packages/mainline/debian/ stretch nginx" > /etc/apt/sources.list.d/nginx.list \
    && apt-get update \
    && apt-get install -y nginx \
    && rm -f /etc/apt/sources.list.d/nginx.list \
    && apt-key del 7BD9BF62 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /var/www/html \
    && rm -f /etc/nginx/conf.d/default.conf

COPY magento-${magento_version}/nginx/conf.d /etc/nginx/conf.d
COPY magento-${magento_version}/php/conf.d/memory-limit-php.ini /usr/local/etc/php/conf.d/memory-limit-php.ini
COPY magento-${magento_version}/php/conf.d/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

# Install composer & create composer wrapper
RUN usermod -s /bin/bash www-data \
    && (curl -sS https://getcomposer.org/installer | php) || exit 1 \
    && mv composer.phar /usr/local/bin/composer.phar \
    && echo '#!/usr/bin/env bash' >> /usr/local/bin/composer \
    && echo 'COMPOSER_MEMORY_LIMIT=-1 COMPOSER_HOME=/opt/composer/www-data /usr/local/bin/composer.phar $@' >> /usr/local/bin/composer \
    && chmod 0755 /usr/local/bin/composer \
    && mkdir -p /opt/composer/www-data \
    && chown -R www-data:www-data /opt/composer/www-data \
    && find ${magento_path} -type d -exec chmod 777 {} \; \
    && find ${magento_path} -type f -exec chmod 666 {} \; \
    && chown -R www-data:www-data ${magento_path}

USER www-data

# Install Magento
RUN /usr/local/bin/composer config -g http-basic.repo.magento.com bc4c30862f0179e4fb6588d87b42fabc cb1289ea2905db7d27baffcd717c6ed8 \
    && /usr/local/bin/composer -q create-project --repository-url=https://repo.magento.com/ magento/project-community-edition ${magento_path} ${magento_version} \
    && /usr/local/bin/composer config http-basic.repo.magento.com bc4c30862f0179e4fb6588d87b42fabc cb1289ea2905db7d27baffcd717c6ed8 \
    && php ${magento_path}/bin/magento sampledata:deploy \
    && /usr/local/bin/composer clear-cache

COPY --chown=www-data:www-data magento-${magento_version}/magento/styles.css ${magento_path}/pub/media/styles.css
COPY --chown=www-data:www-data magento-${magento_version}/magento/env.php ${magento_path}/app/etc/env.php
COPY --chown=www-data:www-data magento-${magento_version}/magento/config.php ${magento_path}/app/etc/config.php

# Install cron file
COPY --chown=www-data:www-data magento-${magento_version}/magento/crontab /tmp/crontab
RUN crontab -u www-data /tmp/crontab

USER root

COPY magento-${magento_version}/run /opt/run

EXPOSE 80

CMD bash /opt/run
