#!/bin/bash

function info {
    printf "\033[0;36m===> \033[0;33m${1}\033[0m\n"
}

MAGENTO_PATH=/var/www/magento

info "Sleep 10s, waiting for mysql"
sleep 10

info "Add credentials to magento packages for composer"
runuser -s /bin/sh -c "cd /var/www/magento && /usr/local/bin/composer config http-basic.repo.magento.com bc4c30862f0179e4fb6588d87b42fabc cb1289ea2905db7d27baffcd717c6ed8" www-data

info "Flush chache and generated dir"
rm -rf $MAGENTO_PATH/var/cache/*
rm -rf $MAGENTO_PATH/var/page_cache/*
rm -rf $MAGENTO_PATH/generated/*

if [ $(mysql -N -s -h $DB_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD -e "select count(*) from information_schema.tables where table_schema='$MYSQL_DATABASE' and table_name='core_config_data';") -eq 1 ]; then
	cp $MAGENTO_PATH/app/etc/env.php_sample $MAGENTO_PATH/app/etc/env.php
	info "Configure Magento"
	sed -i -e "s/DB_HOST/$DB_HOST/g" $MAGENTO_PATH/app/etc/env.php
	sed -i -e "s/DB_USER/$MYSQL_USER/g" $MAGENTO_PATH/app/etc/env.php
	sed -i -e "s/DB_PASS/$MYSQL_PASSWORD/g" $MAGENTO_PATH/app/etc/env.php
	sed -i -e "s/DB_NAME/$MYSQL_DATABASE/g" $MAGENTO_PATH/app/etc/env.php

    info "Upgrade Magento"
	runuser -s /bin/sh -c "php /var/www/magento/bin/magento setup:upgrade" www-data
else
	info "Install Magento"
	runuser -s /bin/sh -c "php /var/www/magento/bin/magento setup:install --base-url=http://$DOMAIN \
	--db-host=$DB_HOST --db-name=$MYSQL_DATABASE --db-user=$MYSQL_USER --db-password=$MYSQL_PASSWORD \
	--backend-frontname=admin --admin-firstname=Magento --admin-lastname=User \
	--admin-email=admin@magento.localhost --admin-user=admin --admin-password=password123 \
	--language=pl_PL --currency=PLN --timezone=America/New_York --use-rewrites=1" www-data

	runuser -s /bin/sh -c "php /var/www/magento/bin/magento module:enable \
	Magento_CustomerSampleData \
	Magento_MsrpSampleData \
	Magento_CatalogSampleData \
	Magento_DownloadableSampleData \
	Magento_OfflineShippingSampleData \
	Magento_BundleSampleData \
	Magento_ConfigurableSampleData \
	Magento_ThemeSampleData \
	Magento_ProductLinksSampleData \
	Magento_ReviewSampleData \
	Magento_CatalogRuleSampleData \
	Magento_SwatchesSampleData \
	Magento_GroupedProductSampleData \
	Magento_TaxSampleData \
	Magento_CmsSampleData \
	Magento_SalesRuleSampleData \
	Magento_SalesSampleData \
	Magento_WidgetSampleData \
	Magento_WishlistSampleData" www-data
fi

info "Set deployment mode"
runuser -s /bin/sh -c "php /var/www/magento/bin/magento deploy:mode:set developer" www-data

cron

nginx

php-fpm

while true; do
echo "Everything fine"
sleep 3600
done
