FROM debian:8
MAINTAINER Mateusz Koszutowski <mkoszutowski@divante.pl>

ENV magento_path /var/www/magento
ENV MAGENTO_VERSION 1.9.3.3
ENV PHP_SERVICE php5-fpm

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    curl \
    git \
    unzip \
    apt-utils \
    rsync \
    sudo \
    nginx \
    mysql-client \
    php5 \
    php5-fpm \
    php5-cli \
    php5-mysql \
    php5-mcrypt \
    php5-curl \
    php5-gd \
    php5-xdebug \
    cron \
    nano \
    mc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Composer
RUN  php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
	&& php composer-setup.php --install-dir=/usr/bin --filename=composer \
	&& php -r "unlink('composer-setup.php');"

# Nginx
COPY magento/nginx/nginx.conf /etc/nginx/nginx.conf
COPY magento/nginx/magento.conf /etc/nginx/sites-available/magento.conf
RUN (cd /etc/nginx/sites-enabled && ln -s ../sites-available/magento.conf magento.conf && rm -rf default)

#Xdebug
RUN echo "xdebug.remote_port=9000" >> /etc/php5/cli/conf.d/20-xdebug.ini \
    && echo "xdebug.remote_enable=1" >> /etc/php5/cli/conf.d/20-xdebug.ini \
    && echo "xdebug.remote_connect_back=1" >> /etc/php5/cli/conf.d/20-xdebug.ini \
    && echo "xdebug.remote_autostart=1" >> /etc/php5/cli/conf.d/20-xdebug.ini \
    && echo "xdebug.remote_port=9000" >> /etc/php5/fpm/conf.d/20-xdebug.ini \
    && echo "xdebug.remote_enable=1" >> /etc/php5/fpm/conf.d/20-xdebug.ini \
    && echo "xdebug.remote_connect_back=1" >> /etc/php5/fpm/conf.d/20-xdebug.ini \
    && echo "xdebug.remote_autostart=1" >> /etc/php5/fpm/conf.d/20-xdebug.ini

# Magento
RUN curl https://codeload.github.com/OpenMage/magento-mirror/tar.gz/$MAGENTO_VERSION -o /tmp/$MAGENTO_VERSION.tar.gz \
    && tar xf /tmp/$MAGENTO_VERSION.tar.gz -C /tmp \
    && mv /tmp/magento-mirror-$MAGENTO_VERSION ${magento_path} \
    && find ${magento_path} -type d -exec chmod 770 {} \; && find ${magento_path} -type f -exec chmod 660 {} \; \
    && chown -R :www-data ${magento_path}

# Download Sample Data
RUN curl -L https://sourceforge.net/projects/mageloads/files/assets/1.9.2.4/magento-sample-data-1.9.2.4-fix.tar.gz/download -o ${magento_path}/magento-sample-data-1.9.2.4-fix.tar.gz \
    && tar xf ${magento_path}/magento-sample-data-1.9.2.4-fix.tar.gz -C ${magento_path} \
    && rsync -avzhq ${magento_path}/magento-sample-data-1.9.2.4/ ${magento_path}

# Download Magento Translations for Polish
RUN curl -L https://github.com/SnowdogApps/Magento-Translation-pl_PL/archive/master.zip -o /tmp/magento-translation-pl_pl.zip \
    && unzip -o /tmp/magento-translation-pl_pl.zip -d /tmp/ \
    && rsync -avzhq /tmp/Magento-Translation-pl_PL-master/ ${magento_path}/app/locale/

# Install cron file
COPY magento/magento/crontab /tmp/crontab
RUN crontab -u www-data /tmp/crontab

# Fix privileges
RUN find ${magento_path} -type d -exec chmod 770 {} \; && find ${magento_path} -type f -exec chmod 660 {} \; \
    && chown -R :www-data ${magento_path}

COPY magento/run /opt/run

RUN sed -i -e "s/#PHP_SERVICE#/${PHP_SERVICE}/g" /opt/run \
    && sed -i -e "s/#PHP_SERVICE#/${PHP_SERVICE}/g" /etc/nginx/sites-available/magento.conf

EXPOSE 80

CMD bash /opt/run
