FROM debian:9
MAINTAINER Mateusz Koszutowski <mkoszutowski@divante.pl>

ENV magento_path /var/www/magento
ENV MAGENTO_VERSION 1.9.3.10

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    wget \
    gnupg \
    apt-transport-https \
    ca-certificates

RUN wget -q https://packages.sury.org/php/apt.gpg -O- | apt-key add - \
    && echo "deb https://packages.sury.org/php/ stretch main" | tee /etc/apt/sources.list.d/php.list

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    curl \
    git \
    unzip \
    apt-utils \
    rsync \
    sudo \
    nginx \
    mysql-client \
    cron \
    php7.2-cli \
    php7.2-fpm \
    php7.2-curl \
    php7.2-gd \
    php7.2-gmp \
    php7.2-intl \
    php7.2-mbstring \
    php7.2-mysql \
    php7.2-xml \
    php7.2-zip \
    php7.2-bcmath \
    php7.2-soap \
    php7.2-bz2 \
    php7.2-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Composer
RUN  php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
	&& php composer-setup.php --install-dir=/usr/bin --filename=composer \
	&& php -r "unlink('composer-setup.php');"

# Nginx
COPY magento/nginx/nginx.conf /etc/nginx/nginx.conf
COPY magento/nginx/magento.conf /etc/nginx/sites-available/magento.conf
RUN sed -i 's/php5-fpm\.sock/php\/php7\.2-fpm\.sock/' /etc/nginx/sites-available/magento.conf
RUN (cd /etc/nginx/sites-enabled && ln -s ../sites-available/magento.conf magento.conf && rm -rf default)

#Xdebug
RUN echo "xdebug.remote_port=9000" >> /etc/php/7.2/cli/conf.d/20-xdebug.ini \
    && echo "xdebug.remote_enable=1" >> /etc/php/7.2/cli/conf.d/20-xdebug.ini \
    && echo "xdebug.remote_connect_back=1" >> /etc/php/7.2/cli/conf.d/20-xdebug.ini \
    && echo "xdebug.remote_autostart=1" >> /etc/php/7.2/cli/conf.d/20-xdebug.ini \
    && echo "xdebug.remote_port=9000" >> /etc/php/7.2/fpm/conf.d/20-xdebug.ini \
    && echo "xdebug.remote_enable=1" >> /etc/php/7.2/fpm/conf.d/20-xdebug.ini \
    && echo "xdebug.remote_connect_back=1" >> /etc/php/7.2/fpm/conf.d/20-xdebug.ini \
    && echo "xdebug.remote_autostart=1" >> /etc/php/7.2/fpm/conf.d/20-xdebug.ini

# Magento
RUN curl https://storage.googleapis.com/bliskapaczka_magento/magento-1.9.4.0-2018-11-28-04-28-56.zip -o /tmp/magento-1.9.4.0-2018-11-28-04-28-56.zip \
    && unzip -q -d /tmp/magento-1.9.4.0-2018-11-28-04-28-56 /tmp/magento-1.9.4.0-2018-11-28-04-28-56.zip \
    && mv /tmp/magento-1.9.4.0-2018-11-28-04-28-56/magento ${magento_path} \
    && find ${magento_path} -type d -exec chmod 770 {} \; && find ${magento_path} -type f -exec chmod 660 {} \; \
    && chown -R :www-data ${magento_path}

# Download Sample Data
RUN curl -L https://sourceforge.net/projects/mageloads/files/assets/1.9.2.4/magento-sample-data-1.9.2.4-fix.tar.gz/download -o ${magento_path}/magento-sample-data-1.9.2.4-fix.tar.gz \
    && tar xf ${magento_path}/magento-sample-data-1.9.2.4-fix.tar.gz -C ${magento_path} \
    && rsync -avzhq ${magento_path}/magento-sample-data-1.9.2.4/ ${magento_path}

# Download Magento Translations for Polish
RUN curl -L https://github.com/SnowdogApps/Magento-Translation-pl_PL/archive/master.zip -o /tmp/magento-translation-pl_pl.zip \
    && unzip -o /tmp/magento-translation-pl_pl.zip -d /tmp/ \
    && rsync -avzhq /tmp/Magento-Translation-pl_PL-master/ ${magento_path}/app/locale/

# Install cron file
COPY magento/magento/crontab /tmp/crontab
RUN crontab -u www-data /tmp/crontab

# Fix privileges
RUN find ${magento_path} -type d -exec chmod 770 {} \; && find ${magento_path} -type f -exec chmod 660 {} \; \
    && chown -R :www-data ${magento_path}

COPY magento/run /opt/run

EXPOSE 80

CMD bash /opt/run
